# /Users/andrew/.config/tmuxinator/test.yml

name: test
root: .

windows:
  - editor:
      layout: main-horizontal
      panes:
        - terminal:
          - sleep 1 # wait for everything to spin up
          - open http://localhost:4000
        - database-server:
          - postgres -D /usr/local/var/postgres/
        - database-admin:
          - sleep 1 # wait for the postgres server to finish booting
          - psql -d vapor_pg_test
        - backend-server:
          - cd server
          - env DEBUG=1 vapor run
        - http-server:
          - cd web/_site/dev
          - python -m SimpleHTTPServer 4000 --bind localhost
